name: reusable
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: test
        required: false
        default: dist
        type: string
    outputs:
      result: 
        description: test
        value: ${{jobs.deploy.outputs.outcome}}
    secrets:
      some-secret: 
        required: false
jobs:  
  deploy:
    outputs:
      outcome: ${{steps.set-result.outputs.set-result}}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "info"
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
      - name: Set result output
        id: set-result
        run: echo "::set-output name=step-result::success"
      
    
